EOLC T7 export_survey_frequency_graph
THIS-Institute/thiscovery-surveys pull request #66
Opened 2022-09-01 13:13 UTC by sophiemachin

2022-09-02 14:11 UTC, afs25 requested changes
Are all tests passing for you? Two (test_export_survey_frequency_graph and test_make_chart) are failing for me.

2022-09-06 11:42 UTC, sophiemachin commented on admin_tasks/common/highcharts_utilities.py
> +        df = df.iloc[2:]
Good spot. This wasn't working for me and I've only just dug around enough to find out why: my Qualtrics account wasn't set to UTC so this cleanup wasn't happening properly.

2022-09-06 13:30 UTC, sophiemachin commented on admin_tasks/common/highcharts_utilities.py
> +                          self.study_groups_definition.items()}
This is redundant now that I'm using self.df, because this already renamed the responses

2022-09-06 16:01 UTC, sophiemachin commented on tests/admin_tasks/test_highcharts_utilities.py
> +        )
It wasn't failing for me. Either way I've removed all references to dev_config.

2022-09-07 13:15 UTC, afs25 approved these changes

2022-09-07 13:15 UTC, afs25 commented on admin_tasks/common/highcharts_utilities.py
> +        df = df.drop('StartDate', axis=1)
I think this is not needed. The dataset/dataframe will contain lots of columns we are not going to use. Is there any point deleting only the StartDate column?

2022-09-07 14:57 UTC, sophiemachin commented on admin_tasks/common/highcharts_utilities.py
> +        df = df.drop('StartDate', axis=1)
Good point, removed

2022-09-07 15:16 UTC, merged